#!/usr/bin/env python3
"""UCT-guided idea search with prior mask pruning based on verifiable signals.

Is this MCTS?
-------------------
This tool implements three of the four standard MCTS stages:

| Stage | This tool | Description |
|---|---|---|
| Selection | ✅ UCT1 | Select among expanded nodes using Q + c·sqrt(ln N_parent / N_child) |
| Expansion | ✅(performed by an external model) | This tool outputs the next node to expand and expansion instructions; the skill invokes an LLM for actual generation |
| Simulation (rollout) | ❌ **Not implemented** | A research idea cannot be randomly simulated to a terminal outcome. Replace rollout with an evaluation value (AlphaZero-style value substitution) |
| Backup | ✅ | Back up evaluation values along the parent chain, updating visits and value_sum |

The precise description is **UCT-guided best-first expansion with value estimates replacing rollout**, not full MCTS with random simulation.

An accurate account of reward
-----------------
`reward = alpha × v_model + (1 - alpha) × v_verifiable`

- `v_model` comes from `scores.composite`, **produced by an LLM**. Using it alone as the search signal amplifies the scoring model's
  systematic bias: more intensive search makes candidates collapse toward proposals favored by the scoring model.
- `v_verifiable` consists of components independent of LLM judgment (retrieval results, rule lookup, structural completeness, measured cost,
  and computed distinctness). `report --provenance` lists the source of every component.
- **alpha defaults to 0.5; an explicit warning is emitted when v_verifiable has no available components.**

Commands
----
init      Initialize search state (use existing unpruned nodes as the root set)
mask      Compute mask hits; --apply writes pruning state (prune before expansion: prior pruning)
select    Select the next node by UCT and print expansion instructions
expand    Register children generated by the external model and record one visit
backup    Back up an evaluation value (derived automatically from scores.composite by default)
report    Search tree, node Q/visits/UCT, budget consumption, mask statistics
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import idea_nodes as N  # noqa: E402  Reuse node I/O and validation

try:
    from dedup_ideas import find_boilerplate, same_lineage, similarity
except Exception:      # pragma: no cover - Degrade when the deduplication tool is unavailable
    find_boilerplate = similarity = same_lineage = None

DEFAULT_PATH = Path("outputs/IDEA_NODES.jsonl")
UCT_C = 1.414                # sqrt(2), the standard UCT exploration constant
FIT_THRESHOLD = 12           # Matches idea-gen FILTER_THRESHOLD
CRITIQUE_SATURATION = 3      # Matches Phase 2b: at most 3 ideas per critique


# ---------------------------------------------------------------- masks

def mask_hits(node: dict, all_nodes: list[dict], saturated_reason: str | None = None) -> list[tuple[str, str]]:
    """Return (mask, reason). **Based entirely on verifiable signals, with no subjective LLM judgment.**"""
    hits: list[tuple[str, str]] = []
    scores = node.get("scores") or {}
    cw = node.get("closest_work") or {}

    # 1. Collision: retrieval found close prior work (an external retrieval fact), or novelty verification is incomplete
    if cw.get("ref") and not str(cw.get("delta") or "").strip():
        hits.append(("collision", "closest_work has ref but delta is empty; novelty verification is incomplete, so differences cannot be assessed"))
    if node.get("evidence_collision") is True:
        hits.append(("collision", "Retrieval confirms published work with the same mechanism"))

    # 2. Infeasible validation: protocol lookup marks a theory claim NOT_FEASIBLE and none of the three alternatives was adopted
    claims = node.get("theory_claims") or []
    infeasible = [c for c in claims if c.get("feasibility") == "NOT_FEASIBLE"
                  and not c.get("resolution")]
    if infeasible:
        hits.append(("not_feasible",
                     f"{len(infeasible)}/{len(claims)} theory claims are NOT_FEASIBLE with no alternative adopted"))

    # 3. Researcher fit below threshold (a rule threshold, not model judgment)
    fit = scores.get("researcher_fit")
    if fit is not None and float(fit) < FIT_THRESHOLD:
        hits.append(("fit_below_threshold", f"researcher_fit={fit} < {FIT_THRESHOLD}"))

    # 4. Too many candidates for one critique: prune only **the weakest leaves beyond the limit**; see compute_saturated
    if saturated_reason:
        hits.append(("critique_saturated", saturated_reason))

    # 5. Structural unfalsifiability: a hypothesis without a falsifier cannot be refuted experimentally
    hyp = node.get("hypothesis") or {}
    if hyp.get("core") and not str(hyp.get("falsifier") or "").strip():
        hits.append(("not_feasible", "hypothesis lacks falsifier; the hypothesis is not falsifiable, so no validation experiment can be designed"))
    return hits


def compute_saturated(nodes: list[dict], alpha: float) -> dict[str, str]:
    """When candidates sharing an evidence anchor exceed the limit, flag **the excess leaves with the lowest reward**.

    Two boundaries make the mask mean stop allocating budget to this branch, rather than discard existing work:

    1. Consider only **leaves** (candidates without surviving children). A parent with children represents a branch,
       not a redundant sibling candidate; pruning it would invalidate all its children.
    2. Keep the top `CRITIQUE_SATURATION` by reward and flag only the remainder. The early implementation flagged
       **all** nodes under an anchor, pruning both the parent and its best children.
    """
    live = alive(nodes)
    has_live_child = {n.get("parent_id") for n in live if n.get("parent_id")}
    by_anchor: dict[str, list[dict]] = {}
    for n in live:
        if n.get("id") in has_live_child:
            continue                      # Not a leaf; skip
        for a in ((n.get("generator") or {}).get("anchor", []) or []):
            by_anchor.setdefault(a, []).append(n)

    flagged: dict[str, str] = {}
    for a, group in by_anchor.items():
        if len(group) <= CRITIQUE_SATURATION:
            continue
        ranked = sorted(group, key=lambda n: -reward(n, nodes, alpha)[0])
        for n in ranked[CRITIQUE_SATURATION:]:
            flagged[n["id"]] = (f"Critique {a} has {len(group)} candidate leaves (limit "
                                f"{CRITIQUE_SATURATION}); this node's reward rank is "
                                f"{ranked.index(n) + 1}, beyond the limit")
    return flagged


# ---------------------------------------------------------------- reward

def verifiable_components(node: dict, all_nodes: list[dict]) -> dict[str, tuple[float, str]]:
    """Components -> (value 0-1, source description). Missing components are excluded from the average."""
    out: dict[str, tuple[float, str]] = {}
    cw = node.get("closest_work") or {}
    if cw.get("ref"):
        out["retrieval"] = (0.0 if node.get("evidence_collision") is True
                            else (1.0 if str(cw.get("delta") or "").strip() else 0.0),
                            "External retrieval results (published work with the same mechanism found / delta provided)")
    claims = node.get("theory_claims") or []
    if claims:
        ok = sum(1 for c in claims if c.get("feasibility") in ("FEASIBLE", "CAVEATS"))
        out["feasibility_rule"] = (ok / len(claims),
                                   "Claim type -> validation protocol lookup (rules, not model scores)")
    hyp = node.get("hypothesis") or {}
    if hyp.get("core"):
        out["falsifiability"] = (1.0 if str(hyp.get("falsifier") or "").strip() else 0.0,
                                 "Structural completeness: whether a falsifier is provided")
    cost = node.get("cost") or {}
    if cost.get("tokens_total") or cost.get("tokens_in"):
        spent = float(cost.get("tokens_total") or 0) or \
                float(cost.get("tokens_in") or 0) + float(cost.get("tokens_out") or 0)
        peers = []
        for m in all_nodes:
            c = m.get("cost") or {}
            v = float(c.get("tokens_total") or 0) or \
                float(c.get("tokens_in") or 0) + float(c.get("tokens_out") or 0)
            if v:
                peers.append(v)
        if peers and max(peers) > 0:
            out["cost_efficiency"] = (1.0 - min(1.0, spent / max(peers)),
                                      "Measured token usage (lower cost scores higher)")
    if similarity and find_boilerplate and len(all_nodes) > 1:
        boiler = find_boilerplate(all_nodes)
        by_id = {n.get("id"): n for n in all_nodes}
        # Consistent with dedup_ideas: ancestors and descendants are naturally similar (children inherit the parent's framework),
        # so exclude them from the distinctness penalty; compare only candidates outside the lineage.
        sims = [similarity(node, m, boiler)[0] for m in all_nodes
                if m.get("id") != node.get("id")
                and not (same_lineage and same_lineage(node, m, by_id))]
        if sims:
            out["distinctness"] = (1.0 - min(1.0, max(sims)),
                                   "Lexical/concept overlap with **candidates outside the lineage** (computed, not model judgment)")
    return out


def reward(node: dict, all_nodes: list[dict], alpha: float) -> tuple[float, dict]:
    comp = (node.get("scores") or {}).get("composite")
    v_model = float(comp) / 10.0 if comp is not None else None
    comps = verifiable_components(node, all_nodes)
    v_ver = (sum(v for v, _ in comps.values()) / len(comps)) if comps else None

    if v_model is None and v_ver is None:
        return 0.5, {"note": "No signals available; use 0.5"}
    if v_ver is None:
        return v_model, {"v_model": v_model, "v_verifiable": None,
                         "warning": "No verifiable components; reward comes entirely from LLM scores (amplifying scoring bias)"}
    if v_model is None:
        return v_ver, {"v_model": None, "v_verifiable": v_ver,
                       "note": "No LLM scores; reward comes entirely from verifiable components"}
    return (alpha * v_model + (1 - alpha) * v_ver,
            {"v_model": round(v_model, 3), "v_verifiable": round(v_ver, 3), "alpha": alpha,
             "components": {k: round(v, 3) for k, (v, _) in comps.items()}})


# ---------------------------------------------------------------- search state

def s(node: dict) -> dict:
    return node.setdefault("search", {"visits": 0, "value_sum": 0.0,
                                     "expanded": False, "expansions": 0})


def q(node: dict) -> float:
    st = s(node)
    return st["value_sum"] / st["visits"] if st["visits"] else 0.0


def uct(node: dict, parent_visits: int, c: float) -> float:
    st = s(node)
    if st["visits"] == 0:
        return float("inf")
    return q(node) + c * math.sqrt(math.log(max(parent_visits, 1)) / st["visits"])


def children_of(nodes: list[dict], nid: str | None) -> list[dict]:
    return [n for n in nodes if n.get("parent_id") == nid]


# States eligible for expansion: pending (awaiting validation) and supported (supported and open to further investigation).
# Do not allocate further expansion budget to shelved / refuted / impl_failed / pruned nodes;
# they **remain in the file**, because pruning and shelving records are themselves artifacts.
SELECTABLE_STATUS = {"pending", "supported"}


def alive(nodes: list[dict]) -> list[dict]:
    return [n for n in nodes
            if not (n.get("prune") or {}).get("pruned")
            and n.get("status") in SELECTABLE_STATUS]


# ---------------------------------------------------------------- commands

def cmd_init(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    if not nodes:
        print(f"{path} is empty; add candidates with tools/idea_nodes.py first", file=sys.stderr)
        return 1
    for n in nodes:
        st = s(n)
        st.setdefault("visits", 0)
        st.setdefault("value_sum", 0.0)
        st.setdefault("expanded", False)
        st.setdefault("expansions", 0)
    meta = {"budget_expansions": args.budget, "alpha": args.alpha, "uct_c": args.c}
    Path(args.state).write_text(json.dumps(meta, ensure_ascii=False, indent=2), encoding="utf-8")
    N.save(path, nodes)
    print(f"Search initialized: {len(nodes)} nodes, expansion budget {args.budget}, alpha={args.alpha}, c={args.c}")
    print(f"Search parameters saved to {args.state}")
    return 0


def cmd_mask(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    meta = json.loads(Path(args.state).read_text(encoding="utf-8")) if Path(args.state).exists() else {}
    alpha = meta.get("alpha", 0.5)
    saturated = compute_saturated(nodes, alpha)
    rows = []
    for n in alive(nodes):
        hits = mask_hits(n, nodes, saturated.get(n["id"]))
        if hits:
            rows.append((n, hits))
    if not rows:
        print(f"✅ No mask hits ({len(alive(nodes))} surviving nodes)")
        return 0
    print(f"⚠️ {len(rows)} nodes match masks (prior pruning before expansion)\n")
    for n, hits in rows:
        print(f"  {n['id']} {n.get('title','')[:56]}")
        for mask, why in hits:
            print(f"      [{mask}] {why}")
    if args.apply:
        for n, hits in rows:
            mask, why = hits[0]
            n["status"] = "pruned"
            n["prune"] = {"pruned": True, "mask": mask, "reason": why,
                          "all_hits": [{"mask": m, "reason": w} for m, w in hits]}
        N.save(path, nodes)
        print(f"\nPruned {len(rows)} nodes (retained in the file, not deleted)")
        print("prune.all_hits records every reason for each pruned node, enabling later analysis of pruning precision")
    else:
        print("\n(Nothing written. Add --apply to prune.)")
    return 0


def cmd_select(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    meta = json.loads(Path(args.state).read_text(encoding="utf-8")) if Path(args.state).exists() else {}
    c = args.c if args.c is not None else meta.get("uct_c", UCT_C)
    alpha = args.alpha if args.alpha is not None else meta.get("alpha", 0.5)

    pool = alive(nodes)
    if not pool:
        print("No surviving nodes to expand (all were pruned)", file=sys.stderr)
        return 1
    saturated = compute_saturated(nodes, alpha)
    blocked = [n for n in pool if mask_hits(n, nodes, saturated.get(n["id"]))]
    if blocked:
        print(f"⚠️ {len(blocked)} surviving nodes match masks but have not been pruned: "
              f"{[n['id'] for n in blocked]}")
        print("   Run `mask --apply` first; otherwise search spends budget on branches that should be pruned\n")

    total_visits = sum(s(n)["visits"] for n in pool) or 1
    ranked = sorted(pool, key=lambda n: -uct(n, total_visits, c))
    best = ranked[0]
    r, detail = reward(best, nodes, alpha)

    print(f"Next node to expand: **{best['id']}** {best.get('title','')[:60]}")
    st = s(best)
    u = uct(best, total_visits, c)
    print(f"  visits={st['visits']}  Q={q(best):.3f}  UCT={'∞ (unvisited)' if u == float('inf') else f'{u:.3f}'}")
    print(f"  Current reward={r:.3f}  {detail}")
    if detail.get("warning"):
        print(f"  ⚠️ {detail['warning']}")
    print(f"\nCandidate ranking (top 5 by UCT)")
    for n in ranked[:5]:
        u2 = uct(n, total_visits, c)
        print(f"    {n['id']:<14} visits={s(n)['visits']:<3} Q={q(n):.3f} "
              f"UCT={'∞' if u2 == float('inf') else f'{u2:.3f}'}")

    print(f"\n--- Expansion instructions (for the external model)---")
    print(f"Generate {args.k} **mechanistically distinct** child candidates for {best['id']} ({best.get('title','')}).")
    print("Each child candidate must:")
    print("  1. Be anchored to a specific evidence ID (CRITIQUE-xx / C-xx / failure condition); it must not be empty")
    print("  2. Provide hypothesis.core and a **falsifier** (the result that would refute it)")
    print("  3. Provide closest_work ref and delta (missing delta triggers the collision mask)")
    print("  4. Differ from the parent in **mechanism**, not merely wording")
    print(f"Save the result as a JSON array, then:")
    print(f"  python3 tools/mcts_search.py expand {best['id']} --children <file.json>")
    return 0


def cmd_expand(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    parent = next((n for n in nodes if n.get("id") == args.id), None)
    if parent is None:
        print(f"Node {args.id} not found", file=sys.stderr)
        return 1
    payload = json.loads(Path(args.children).read_text(encoding="utf-8"))
    incoming = payload if isinstance(payload, list) else [payload]
    known = {n.get("id") for n in nodes}
    problems, added = [], []
    for child in incoming:
        child["parent_id"] = args.id
        child.setdefault("status", "pending")
        child.setdefault("created_at", N._now())
        child["updated_at"] = N._now()
        if child.get("id") in known:
            problems.append(f"{child.get('id')}: duplicate id")
            continue
        errs = N.validate_node(child, known | {c.get("id") for c in incoming})
        if errs:
            problems.extend(errs)
            continue
        s(child)
        nodes.append(child)
        known.add(child.get("id"))
        added.append(child)
    if problems:
        print("Child-node validation failed; nothing written:", file=sys.stderr)
        for p_ in problems:
            print(f"  - {p_}", file=sys.stderr)
        return 1
    st_parent = s(parent)
    st_parent["expanded"] = True
    # Expansion does **not** increment visits: each UCT visit must have a backed-up value,
    # otherwise value_sum/visits is diluted and selection avoids newly expanded nodes.
    # Track budget separately through expansions.
    st_parent["expansions"] = st_parent.get("expansions", 0) + 1
    N.save(path, nodes)
    print(f"Registered {len(added)} children for {args.id}: {[c['id'] for c in added]}")
    print(f"  {args.id} expansions -> {st_parent['expansions']}(visits unchanged; awaiting backup)")
    print("Next score the children (/idea-screen), then back up values:")
    for c in added:
        print(f"  python3 tools/mcts_search.py backup {c['id']}")
    return 0


def cmd_backup(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    by_id = {n.get("id"): n for n in nodes}
    node = by_id.get(args.id)
    if node is None:
        print(f"Node {args.id} not found", file=sys.stderr)
        return 1
    meta = json.loads(Path(args.state).read_text(encoding="utf-8")) if Path(args.state).exists() else {}
    alpha = args.alpha if args.alpha is not None else meta.get("alpha", 0.5)
    if args.value is not None:
        r, detail = float(args.value), {"note": "Manually specified"}
    else:
        r, detail = reward(node, nodes, alpha)

    chain, cur, guard = [], node, 0
    while cur is not None and guard < 50:
        st = s(cur)
        st["visits"] += 1
        st["value_sum"] += r
        chain.append(f"{cur['id']}(visits={st['visits']}, Q={q(cur):.3f})")
        cur = by_id.get(cur.get("parent_id"))
        guard += 1
    N.save(path, nodes)
    print(f"Backed-up reward={r:.3f} {detail}")
    if detail.get("warning"):
        print(f"⚠️ {detail['warning']}")
    print("Updated path: " + " → ".join(chain))
    return 0


def cmd_report(args) -> int:
    path = Path(args.path)
    nodes = N.load(path)
    meta = json.loads(Path(args.state).read_text(encoding="utf-8")) if Path(args.state).exists() else {}
    alpha = args.alpha if args.alpha is not None else meta.get("alpha", 0.5)
    c = meta.get("uct_c", UCT_C)
    pool = alive(nodes)
    total_visits = sum(s(n)["visits"] for n in pool) or 1

    print("=" * 70)
    print("Search tree")
    print("=" * 70)

    def walk(parent_id, depth):
        for n in sorted(children_of(nodes, parent_id), key=lambda x: -q(x)):
            st = s(n)
            pruned = (n.get("prune") or {}).get("pruned")
            selectable = not pruned and n.get("status") in SELECTABLE_STATUS
            if pruned:
                tag = f"  ✂ {(n.get('prune') or {}).get('mask')}"
            elif not selectable:
                tag = f"  ⏸ {n.get('status')}"
            else:
                tag = ""
            u = uct(n, total_visits, c)
            # Ineligible nodes (pruned / shelved / refuted / impl_failed) are excluded from selection;
            # showing UCT would imply they remain in the candidate pool
            us = "—" if not selectable else ("∞" if u == float("inf") else f"{u:.2f}")
            print(f"{'  ' * depth}{'└─ ' if depth else ''}{n['id']:<14} "
                  f"visits={st['visits']:<3} Q={q(n):.3f} UCT={us:<6} "
                  f"{n.get('title','')[:38]}{tag}")
            walk(n.get("id"), depth + 1)

    walk(None, 0)

    expansions = sum(s(n).get("expansions", 1 if s(n).get("expanded") else 0) for n in nodes)
    budget = meta.get("budget_expansions")
    print(f"\nExpansions: {expansions}" + (f" / budget {budget}" if budget else ""))
    if budget and expansions >= budget:
        print("  ⚠️ Expansion budget exhausted")

    masks: dict[str, int] = {}
    for n in nodes:
        pr = n.get("prune") or {}
        if pr.get("pruned"):
            masks[pr.get("mask", "?")] = masks.get(pr.get("mask", "?"), 0) + 1
    if masks:
        print("Pruning statistics: " + ", ".join(f"{k}={v}" for k, v in sorted(masks.items())))
        print("  Pruning precision requires human review: how many pruned nodes actually warranted pruning")

    tok = sum(float((n.get("cost") or {}).get("tokens_total") or 0) for n in nodes)
    calls = sum(float((n.get("cost") or {}).get("external_calls") or 0) for n in nodes)
    if tok or calls:
        print(f"Cumulative cost: tokens_total={tok:g}, external_calls={calls:g}")

    if args.provenance:
        print("\n" + "=" * 70)
        print("Reward-component provenance (per node)")
        print("=" * 70)
        n_llm_only = 0
        for n in pool:
            r, detail = reward(n, nodes, alpha)
            comps = verifiable_components(n, nodes)
            print(f"\n  {n['id']}  reward={r:.3f}")
            print(f"    v_model      = {detail.get('v_model')}   ← LLM score (scores.composite)")
            print(f"    v_verifiable = {detail.get('v_verifiable')}")
            for k, (v, src) in comps.items():
                print(f"        {k:<17}={v:.3f}  ← {src}")
            if not comps:
                n_llm_only += 1
                print("        (no verifiable components)")
        if n_llm_only:
            print(f"\n⚠️ {n_llm_only}/{len(pool)} nodes have rewards derived entirely from LLM scores.")
            print("   Expanding search in this situation amplifies the scoring model's preferences without improving idea quality.")
            print("   See the README Roadmap entry on non-LLM reward signals for potential remedies.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--path", default=str(DEFAULT_PATH))
    ap.add_argument("--state", default="outputs/SEARCH_STATE.json")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("init"); p.add_argument("--budget", type=int, default=8)
    p.add_argument("--alpha", type=float, default=0.5); p.add_argument("--c", type=float, default=UCT_C)
    p.set_defaults(func=cmd_init)

    p = sub.add_parser("mask"); p.add_argument("--apply", action="store_true")
    p.set_defaults(func=cmd_mask)

    p = sub.add_parser("select"); p.add_argument("-k", type=int, default=3)
    p.add_argument("--c", type=float, default=None); p.add_argument("--alpha", type=float, default=None)
    p.set_defaults(func=cmd_select)

    p = sub.add_parser("expand"); p.add_argument("id"); p.add_argument("--children", required=True)
    p.set_defaults(func=cmd_expand)

    p = sub.add_parser("backup"); p.add_argument("id"); p.add_argument("--value", type=float, default=None)
    p.add_argument("--alpha", type=float, default=None); p.set_defaults(func=cmd_backup)

    p = sub.add_parser("report"); p.add_argument("--provenance", action="store_true")
    p.add_argument("--alpha", type=float, default=None); p.set_defaults(func=cmd_report)

    args = ap.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
